name: pull-request
on: pull_request

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - name: pnpm install
        run: pnpm install
      - name: lint
        run: pnpm run lint
      - name: format
        run: pnpm run format
