name: pull-request
on: pull_request

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: pnpm install
        run: pnpm install
      - name: lint
        run: pnpm run lint
      - name: format
        run: pnpm run format
